#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR;

BACKUP=../backup-daily-dir
TMP=../tmp-daily
mkdir -p $BACKUP;

prepare-backup() {
  rm -rf $TMP && mkdir $TMP;
}
do-backup() {
  rdiff-backup $TMP $BACKUP/$1;

  rm -rf $TMP;
  # Delete old entries
  rdiff-backup --force --remove-older-than 1M $BACKUP/$1;
}

backup-example() {
  prepare-backup;

  # setup TMP with backup here

  do-backup "backup-name";
}

backup-example;
